export interface Theme {
  id: string;
  name: string;
  colors: Record<string, string>;
}

export const themes: Theme[] = [
  {
    id: "dark",
    name: "Dark",
    colors: {
      "--bg-deep": "#18191c",
      "--bg-primary": "#1c1d20",
      "--bg-secondary": "#222327",
      "--bg-tertiary": "#2a2b30",
      "--bg-hover": "#32333a",
      "--bg-active": "#2c5daa",
      "--border": "#3a3b42",
      "--text-primary": "#e8e9ed",
      "--text-secondary": "#a0a2b0",
      "--text-muted": "#6a6c7a",
      "--accent": "#4a90e2",
      "--accent-hover": "#5ba0f2",
      "--danger": "#e25555",
      "--success": "#4abb8a",
      "--warning": "#e2a94a",
      "--scrollbar-thumb": "#454650",
      "--scrollbar-thumb-hover": "#555665",
      "--separator": "#35363d",
      "--selected-hover": "#3268b8",
      "--dir-color": "#4a9eff",
    },
  },
  {
    id: "light",
    name: "Light",
    colors: {
      "--bg-deep": "#f0f1f4",
      "--bg-primary": "#f7f8fa",
      "--bg-secondary": "#ffffff",
      "--bg-tertiary": "#e8eaef",
      "--bg-hover": "#dfe1e8",
      "--bg-active": "#3a7bd5",
      "--border": "#d0d3db",
      "--text-primary": "#1a1d26",
      "--text-secondary": "#4a4f5e",
      "--text-muted": "#8a8f9e",
      "--accent": "#3a7bd5",
      "--accent-hover": "#2d6bc4",
      "--danger": "#d33a3a",
      "--success": "#2d9d6f",
      "--warning": "#c98a2e",
      "--scrollbar-thumb": "#c0c3cc",
      "--scrollbar-thumb-hover": "#a8abb5",
      "--separator": "#d8dae0",
      "--selected-hover": "#2d6bc4",
      "--dir-color": "#2b6cb0",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    colors: {
      "--bg-deep": "#21252b",
      "--bg-primary": "#282c34",
      "--bg-secondary": "#2c313a",
      "--bg-tertiary": "#333842",
      "--bg-hover": "#3a3f4b",
      "--bg-active": "#2c5daa",
      "--border": "#3e4452",
      "--text-primary": "#abb2bf",
      "--text-secondary": "#8b929e",
      "--text-muted": "#5c6370",
      "--accent": "#61afef",
      "--accent-hover": "#74baff",
      "--danger": "#e06c75",
      "--success": "#98c379",
      "--warning": "#e5c07b",
      "--scrollbar-thumb": "#484d58",
      "--scrollbar-thumb-hover": "#585e6a",
      "--separator": "#3b4048",
      "--selected-hover": "#3572c4",
      "--dir-color": "#61afef",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    colors: {
      "--bg-deep": "#1e1f29",
      "--bg-primary": "#282a36",
      "--bg-secondary": "#2d2f3d",
      "--bg-tertiary": "#343746",
      "--bg-hover": "#3c3f58",
      "--bg-active": "#6272a4",
      "--border": "#44475a",
      "--text-primary": "#f8f8f2",
      "--text-secondary": "#c0c0d0",
      "--text-muted": "#6272a4",
      "--accent": "#bd93f9",
      "--accent-hover": "#caa4ff",
      "--danger": "#ff5555",
      "--success": "#50fa7b",
      "--warning": "#f1fa8c",
      "--scrollbar-thumb": "#44475a",
      "--scrollbar-thumb-hover": "#555870",
      "--separator": "#44475a",
      "--selected-hover": "#7283b5",
      "--dir-color": "#8be9fd",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin",
    colors: {
      "--bg-deep": "#181825",
      "--bg-primary": "#1e1e2e",
      "--bg-secondary": "#24243e",
      "--bg-tertiary": "#313244",
      "--bg-hover": "#3b3c52",
      "--bg-active": "#585b70",
      "--border": "#45475a",
      "--text-primary": "#cdd6f4",
      "--text-secondary": "#a6adc8",
      "--text-muted": "#6c7086",
      "--accent": "#89b4fa",
      "--accent-hover": "#9cc3ff",
      "--danger": "#f38ba8",
      "--success": "#a6e3a1",
      "--warning": "#f9e2af",
      "--scrollbar-thumb": "#45475a",
      "--scrollbar-thumb-hover": "#585b70",
      "--separator": "#45475a",
      "--selected-hover": "#6880b0",
      "--dir-color": "#89dceb",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    colors: {
      "--bg-deep": "#16161e",
      "--bg-primary": "#1a1b26",
      "--bg-secondary": "#1f2335",
      "--bg-tertiary": "#24283b",
      "--bg-hover": "#292e42",
      "--bg-active": "#33467c",
      "--border": "#3b4261",
      "--text-primary": "#c0caf5",
      "--text-secondary": "#a9b1d6",
      "--text-muted": "#565f89",
      "--accent": "#7aa2f7",
      "--accent-hover": "#8db0ff",
      "--danger": "#f7768e",
      "--success": "#9ece6a",
      "--warning": "#e0af68",
      "--scrollbar-thumb": "#3b4261",
      "--scrollbar-thumb-hover": "#4e5579",
      "--separator": "#3b4261",
      "--selected-hover": "#3d5090",
      "--dir-color": "#7dcfff",
    },
  },
  {
    id: "rose-pine",
    name: "Rose Pine",
    colors: {
      "--bg-deep": "#1a1826",
      "--bg-primary": "#191724",
      "--bg-secondary": "#1f1d2e",
      "--bg-tertiary": "#26233a",
      "--bg-hover": "#2e2b3f",
      "--bg-active": "#524f67",
      "--border": "#3a3650",
      "--text-primary": "#e0def4",
      "--text-secondary": "#b8b0cc",
      "--text-muted": "#6e6a86",
      "--accent": "#c4a7e7",
      "--accent-hover": "#d4bbf5",
      "--danger": "#eb6f92",
      "--success": "#9ccfd8",
      "--warning": "#f6c177",
      "--scrollbar-thumb": "#3a3650",
      "--scrollbar-thumb-hover": "#4d4868",
      "--separator": "#3a3650",
      "--selected-hover": "#605c78",
      "--dir-color": "#9ccfd8",
    },
  },
  {
    id: "nightfox",
    name: "Nightfox",
    colors: {
      "--bg-deep": "#131a24",
      "--bg-primary": "#192330",
      "--bg-secondary": "#1d2a3a",
      "--bg-tertiary": "#233345",
      "--bg-hover": "#29394d",
      "--bg-active": "#2b4f7a",
      "--border": "#2b3b51",
      "--text-primary": "#cdcecf",
      "--text-secondary": "#9da3b0",
      "--text-muted": "#5a6475",
      "--accent": "#719cd6",
      "--accent-hover": "#84b0e8",
      "--danger": "#c94f6d",
      "--success": "#81b29a",
      "--warning": "#dbc074",
      "--scrollbar-thumb": "#2b3b51",
      "--scrollbar-thumb-hover": "#3b4d65",
      "--separator": "#2b3b51",
      "--selected-hover": "#35618c",
      "--dir-color": "#63cdcf",
    },
  },
  {
    id: "gruvbox",
    name: "Gruvbox",
    colors: {
      "--bg-deep": "#1d2021",
      "--bg-primary": "#282828",
      "--bg-secondary": "#32302f",
      "--bg-tertiary": "#3c3836",
      "--bg-hover": "#504945",
      "--bg-active": "#4a6a40",
      "--border": "#504945",
      "--text-primary": "#ebdbb2",
      "--text-secondary": "#bdae93",
      "--text-muted": "#7c6f64",
      "--accent": "#83a598",
      "--accent-hover": "#8ec07c",
      "--danger": "#fb4934",
      "--success": "#b8bb26",
      "--warning": "#fabd2f",
      "--scrollbar-thumb": "#504945",
      "--scrollbar-thumb-hover": "#665c54",
      "--separator": "#504945",
      "--selected-hover": "#5a7a50",
      "--dir-color": "#83a598",
    },
  },
];

export function getTheme(id: string): Theme {
  return themes.find((t) => t.id === id) || themes[0];
}

export function applyTheme(id: string) {
  const theme = getTheme(id);
  const root = document.documentElement;
  for (const [key, value] of Object.entries(theme.colors)) {
    root.style.setProperty(key, value);
  }
  localStorage.setItem("ziprs-theme", id);
}

export function loadSavedTheme(): string {
  const saved = localStorage.getItem("ziprs-theme") || "dark";
  applyTheme(saved);
  return saved;
}
